apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: partner-catalog
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/ebannon-tenant/partner-catalog/partner-catalog@sha256:2babfe68b90c8df9be1e92951abd0a95dea9bebc77c0f30a5096bc9f68e074dd
        name: my-java-springboot
        resources: {}
status: {}
